[build]
  command = "npm run build"
  publish = "dist"

# Netlify functions configuration
[functions]
  directory = "netlify/functions"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200