[build]
  command = "npm run build"
  publish = "dist"

# Netlify functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Include the Astro DB file and directory in the function bundle
  included_files = [".astro/**/*"]

[build.environment]
  ASTRO_DATABASE_FILE = "sqlite:.astro/content.db"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry-server"
  status = 200